# Generated by Django 3.0 on 2025-08-15 09:20

from django.db import migrations


def transfer_profiles_data(apps, schema_editor):
    OldProfile = apps.get_model("oc_lettings_site", "Profile")
    NewProfile = apps.get_model("profiles", "Profile")

    # Transférer les adresses
    for old_profile in OldProfile.objects.all():
        NewProfile.objects.create(
            user=old_profile.user,
            favorite_city=old_profile.favorite_city,
        )


def reverse_transfer_letting_data(apps, schema_editor):
    # Logique pour annuler la migration
    NewProfile = apps.get_model("profiles", "Profile")

    # Supprimer les objets créés
    NewProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(transfer_profiles_data, reverse_transfer_letting_data),
    ]
