# Generated by Django 5.2.6 on 2025-09-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_data_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='letting',
            options={'verbose_name_plural': 'Lettings'},
        ),
    ]
