# Generated by Django 3.0 on 2025-08-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0001_initial"),
        # Assurez-vous que cette migration dépend des migrations
        # de données pour que le transfert soit fait avant la suppression.
        ("lettings", "0002_data_migration"),
        ("profiles", "0002_data_migration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Letting",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
