name: Docker Image CI

on:
  push:
    branches: [ "main", "QA" ]
    paths-ignore:
      - '.readthedocs.yaml'
      - 'docs/**'
      - '**.md'
      - '.github/**'
      
  workflow_dispatch: # Permet de déclencher ce workflow manuellement depuis l'interface GitHub

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

      - name: Run Django tests
        run: coverage run manage.py test && coverage report --fail-under=80
        
  build_and_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: build_and_test
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/oc_projet13:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    if: github.ref_name == 'main'
    steps:
      - name: Trigger Render Deploy Hook
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK }}
          DOCKER_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/oc_projet13:${{ github.sha }}
        run: |
          # Forme l'URL complète avec le paramètre imgURL pour spécifier le tag
          # Le paramètre imgURL doit être encodé en URL, le `|` dans la syntaxe `run` aide à le formater correctement.
          DEPLOY_URL="${RENDER_DEPLOY_HOOK_URL}?imgURL=${DOCKER_IMAGE_TAG}"
          curl -X POST "$DEPLOY_URL"
