name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/**' # Déclenche le workflow si des fichiers dans le dossier 'app' sont modifiés
      - 'tests/**' # Déclenche aussi si des modifications dans le dossier 'tests'
      - 'requirements.txt' # Déclenche si les dépendances changent
      
  workflow_dispatch: # Permet de déclencher ce workflow manuellement depuis l'interface GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

      - name: Run Django tests
        run: coverage run manage.py test && coverage report --fail-under=80

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/oc_projet13:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
